common: &common
  weibo:
    app_key: "83541187"
    app_secret: "70968cae2cbaf5bf060878d5b169691e"
    redirect_uri: "http://17up.org/members/auth/weibo/callback"
  google:
    app_id: "995938770204.apps.googleusercontent.com"
    app_secret: "SlHYWozODCEj0mWAb1X3qBFS"
    api_key: "AIzaSyDrx8B0GDF3Nvg4skDM82MlV0bRm8rwQtc"
    redirect_uri: "http://17up.org/members/auth/google_oauth2/callback"
  twitter:
    app_key: 'jNkSGziKmcUyEVO1Ln8VNw'
    app_secret: 'jHXBVAUuigM0StpxCEISTcGj5l42uz83Ih2NViSia8'
    redirect_uri: "http://17up.org/members/auth/twitter/callback"
  github:
    client_id: "2c2584f70b84e62ac922"
    client_secret: "d0c9f640da4b4bbce2137096cdff38969dae8e40"
    redirect_uri: "http://17up.org/members/auth/github/callback"
  tumblr:
    app_key: "wMLNMIkDwcoVH4cU41UY82qBhx4ZQLeiJaD3QMvVUhrebAarfx"
    app_secret: "myKcSerbXbpM1dEOxyjKM4ccI1DJkV9OKAHHmGjtiQDjxnYTk1"
    redirect_uri: "http://17up.org/members/auth/tumblr/callback"
  instagram:
    client_id: "47482a8ef25644cbba08bce0865ed701"
    client_secret: "329e141044144b4b96d0b868cd95a1de"
    redirect_uri: "http://17up.org/members/auth/instagram/callback"
  bing:
    client_id: "b3bf0ac2-5720-431d-a86f-36278fd283c3"
    client_secret: "5yU9IMsoDy58AWBGaFdlumQ/OaIVObnCi8j2mry3Rew="
  500px:
    app_key: "Yn6OsCTsYFrjnQZHBETst8ArbvjXnjd26PBjcJKV"
    app_secret: "vNK9mDo8YHmgcwWzMbAWKNKxJDjjPxEFl2GwwpPW"
    user_name: "veggie89"
    password: "fuckgcd"
  goodreads:
    app_key: "mhzPsbPg5I7KjFxS6vGow"
    app_secret: "TKXwsW71uoufYrDj8JupP1BB3WEqDVd4QwtbYtp9AM"
  imgur:
    client_id: "13d34090a9cfa5e"
    client_secret: "0bdb6663a5803dc788599049f31b6cf417f71575"
    redirect_uri: "http://17up.org/members/auth/imgur/callback"
  place:
    app_key: "AIzaSyB3-v9TZ2q_s1NQGxqO0R_I6qUgAe-_ilI"
    app_secret: "59c7da768a5d4423bfe88d26a00c3e22"
  youtube:
    app_key: "AI39si7FCw_BIq-gyPw3oNa6UkItec5eKwbtu9etmXour7UwCi6BE4hTkvFoPGMDU43lKAr1Gjk6DF4bnZOgaBtga-HtEyZ6Lg"
  evernote:
    app_key: "heartme"
    app_secret: "f4d03891fc7d58ed"
production:
  <<: *common

development:
  <<: *common

test:
  <<: *common